### ISSUE TITLE
'Shape' module import error

### ISSUE THREAD

**Issue by hollemantv** [nickrusso42518/slt-py-example#3]
here's what happens when I run complete.py.  (the necessary files all live in the same directory.)  
LY900% ./complete.py
Traceback (most recent call last):
  File "./complete.py", line 15, in <module>
    from shapes.rectangle import Rectangle
ModuleNotFoundError: No module named 'shapes.rectangle'; 'shapes' is not a package

**Comment by nickrusso42518** [comment]
Can you provide the contents of `/usr/lib/python3.8/site-packages/shapes/init.py` please?

**Comment by hollemantv** [comment]
Thanks, Nick. Problem was there was already a 'shapes' module installed (ver0.1.3).  I uninstalled and replaced with yours and it works fine.

**Comment by nickrusso42518** [comment]
Thanks!
